Feature/#1 Transfer widget modal
reef-defi/reef-app pull request #205
Opened 2023-02-02 20:51 UTC by BeneRichi

# Pull Request: Feature/#1 Transfer widget modal

## Description
This pull request adds a new "Transfer Widget Modal" feature to the application. The feature allows users to view their transaction details inside a simple and clear modal with basic informations about their transaction. 

The following changes have been made:
- Build for NFT transfers and Token transfers (More activites will come like : Swap)
- Removed a-tag around ActivityItem in Activity.tsx 
- Created ActivityDetails.tsx modal component with two templates, one for NFT transaction and one for Token transaction
- Save current transaction in state named "selectedTransaction"
- Open modal on click of ActivityItem.tsx 
- Pass necessary props into ActivityDetails.tsx of the selectedTransaction
- Style component in activity-details.css

## Tasks

- [x] Test the feature on different browsers

## Thank you!

Thanks for taking the time to review this pull request. I'm looking forward to your feedback!

2023-02-02 20:53 UTC, BeneRichi commented
@matjazonline Thanks for taking the time to review this pull request.

2023-02-09 06:25 UTC, matjazonline requested changes

2023-02-09 06:25 UTC, matjazonline commented on src/pages/dashboard/Activity/Activity.tsx
> +  const [selectedTransaction, setTransaction] = useState<TokenTransfer|null>(null);
should be setSelectedTransaction

2023-02-09 06:25 UTC, matjazonline commented on src/pages/dashboard/Activity/Activity.tsx
> +          {transfers.slice(0, 10).map((item, index) => (
why take 10 - better if query sets nr of items

2023-02-13 06:50 UTC, BeneRichi commented
@matjazonline Can you explain the reason why there are accounts where a match cannot be found in the signer array, resulting in the inability to retrieve a name for the wallet? I have used "no name" as a fallback solution in these cases.

2023-02-13 17:39 UTC, matjazonline commented
signers array is from accounts in extension and this can occur if account is not present

2023-02-13 17:43 UTC, BeneRichi commented
Got it, make sense. Thanks for clarification.

2023-02-15 06:37 UTC, BeneRichi commented
@matjazonline PR is ready for review.

2023-04-01 16:44 UTC, closed without merging